# version string format -- This will be overwritten later anyway
version: "{build}"

branches:
  except:
    - /dev-travis.+/

os:
  - Visual Studio 2017

environment:
    matrix:
        - additional_flags: "/permissive- /std:c++latest"
          wmain: 0

init:
  - git config --global core.autocrlf true
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - python -m pip install codecov
  - ps: if (($env:CONFIGURATION) -eq "Debug" ) { choco install codecov }

# fetch repository as zip archive
shallow_clone: true

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - Win32
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
#  - Release

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - set CXXFLAGS=%additional_flags%
  # In debug build, we want to
  # 1) Get OpenCppCoverage tool for codecov
  # 2) Regenerate single header include for examples
  # 3) Enable building examples
  - ps: if (($env:CONFIGURATION) -eq "Debug" ) { .\scripts\installOpenCppCoverage.ps1 }
  - python scripts\generateSingleHeader.py
  # Prebuild memcheck redirecter
  - cmake -Hmisc -Bbuild-misc -A%PLATFORM%
  - cmake --build build-misc
  - cmake -H. -BBuild -A%PLATFORM% -DUSE_WMAIN=%wmain% -DBUILD_EXAMPLES=ON -DMEMORYCHECK_COMMAND=build-misc\Debug\CoverageHelper.exe -DMEMORYCHECK_COMMAND_OPTIONS=--sep-- -DMEMORYCHECK_TYPE=Valgrind


# build with MSBuild
build:
  project: Build\CatchSelfTest.sln      # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - set CTEST_OUTPUT_ON_FAILURE=1
  - ctest --verbose -j 2 -C %CONFIGURATION% -D ExperimentalMemCheck
  - ps: |
      if (($env:CONFIGURATION) -eq "Debug" ) {
          Get-Content cobertura1.xml
      }
  - codecov --no-color --disable gcov -f cobertura1.xml cobertura2.xml cobertura3.xml cobertura4.xml cobertura5.xml
# This is for chocolatey codecov
#  - codecov -f cobertura1.xml cobertura2.xml cobertura3.xml cobertura4.xml cobertura5.xml

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
